-- =============================================================================
-- V001__create_auth_schema.sql
-- Context  : auth/user
-- Purpose  : Bootstrap the authentication and user identity schema.
--            Creates: users, user_addresses, refresh_token_families,
--                     refresh_tokens, password_reset_tokens, admin_audit_log.
--            Grants  : ecommerce_app role with least-privilege surface.
--            Trigger : set_updated_at() for users.updated_at.
--
-- Safety analysis
-- ---------------
-- Lock profile  : This is the first migration on an empty database — no live
--                 tables exist, so no ACCESS EXCLUSIVE lock contention.
--                 All DDL here is safe to run inside Flyway's implicit
--                 transaction (no CONCURRENTLY needed; no hot table yet).
-- Destructive?  : No. Greenfield creation only.
-- Backfill?     : No data in schema at this point.
-- Forward-fix   : N/A — no previous version to break.
-- Rollback      : DROP the objects in reverse dependency order (dev only;
--                 production follows expand–migrate–contract — a new version).
-- Testcontainer : Verified from clean (no prior migrations). Previous-version
--                 path does not apply to V001.
-- Applied       : 2026-07-31  (append-only — never modify after first apply)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Extensions
-- ---------------------------------------------------------------------------
-- citext: case-insensitive text for email — DB-level uniqueness is enforced
--         without requiring the application to normalise to lower-case first.
-- pgcrypto: available for digest() if token hashing is ever performed
--           inside the DB (currently hashing is application-side; extension
--           ships now to avoid a schema migration later if needed).
CREATE EXTENSION IF NOT EXISTS "citext";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- 2. Shared trigger function: keep updated_at current
--    Defined once here; reused by every table that carries updated_at.
--    Using CREATE OR REPLACE so subsequent migrations adding new triggers
--    do not have to redefine the function.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 3. Table: users
--    Aggregate root of the auth/user bounded context.
--    ID is UUIDv7, generated application-side (ADR-0002 + security §6a).
--    No DEFAULT on id — omitting it forces every INSERT to supply one
--    explicitly; a missing id fails loudly rather than silently using a
--    DB-generated value of the wrong kind.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                    uuid          NOT NULL,
    email                 citext        NOT NULL,
    email_verified        boolean       NOT NULL DEFAULT false,
    password_hash         text          NOT NULL,

    -- Role: flat CUSTOMER / ADMIN in v1 (security §3.1).
    -- text + CHECK is preferred over a native enum: adding a value is ALTER
    -- TABLE (cheap), not CREATE TYPE + dependency juggling.
    role                  varchar(20)   NOT NULL DEFAULT 'CUSTOMER',

    -- Lockout state written by the application's per-account rate-limiter
    -- (security §2.2). account_locked = true SHORT-CIRCUITS authentication
    -- even if the password is correct.
    account_locked        boolean       NOT NULL DEFAULT false,
    failed_login_attempts smallint      NOT NULL DEFAULT 0,
    locked_at             timestamptz,

    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT ck_users_role
        CHECK (role IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT ck_users_failed_attempts
        CHECK (failed_login_attempts >= 0)
);

COMMENT ON TABLE  users IS
    'Identity and credential store. One row per registered user. '
    'Deletion is NOT permitted while orders/carts reference this row (RESTRICT FKs downstream). '
    'Deactivation uses account_locked = true.';
COMMENT ON COLUMN users.id IS
    'UUIDv7 generated by the application before INSERT (ADR-0002). '
    'No DB default — omitting id in an INSERT is a programmer error, not a silent fallback.';
COMMENT ON COLUMN users.email IS
    'citext ensures case-insensitive uniqueness and lookup without application normalisation. '
    'Unique constraint is the DB-level guard backing the anti-enumeration flow (security §2.1).';
COMMENT ON COLUMN users.password_hash IS
    'BCrypt hash, format $2a$NN$... Strength >= 10 rounds (security §2.1). '
    'Raw password never persisted or logged.';
COMMENT ON COLUMN users.role IS
    'CUSTOMER (default) or ADMIN. New roles require an ADR (security §3.1).';
COMMENT ON COLUMN users.failed_login_attempts IS
    'Incremented on each failed login; reset to 0 on success. '
    'When it reaches the configured threshold the account is locked (account_locked = true, locked_at = now()).';
COMMENT ON COLUMN users.locked_at IS
    'Populated when account_locked is set to true. Used to compute auto-unlock windows if implemented.';

-- Unique index on email (citext automatically handles case folding in comparisons;
-- the index itself stores the value as-is but comparisons are case-insensitive).
-- Named explicitly so the constraint name is predictable in error messages.
CREATE UNIQUE INDEX uq_users_email ON users (email);

-- Trigger: keep updated_at synchronised on every UPDATE row.
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 4. Table: user_addresses
--    Child rows of users (one-to-many, ON DELETE CASCADE).
--    PK is bigint identity — internal child, never client-addressed as an
--    aggregate (ADR-0002 §ID conventions).
-- ---------------------------------------------------------------------------
CREATE TABLE user_addresses (
    id            bigint      GENERATED ALWAYS AS IDENTITY,
    user_id       uuid        NOT NULL,
    label         varchar(50),         -- "Casa", "Trabajo", etc. (nullable)
    street        text        NOT NULL,
    city          varchar(100) NOT NULL,
    state_province varchar(100),
    postal_code   varchar(20),
    country_code  char(2)     NOT NULL,
    is_default    boolean     NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_user_addresses PRIMARY KEY (id),
    CONSTRAINT fk_user_addresses_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_addresses_country_code
        CHECK (char_length(country_code) = 2)
);

COMMENT ON TABLE  user_addresses IS
    'Profile addresses belonging to a registered customer. '
    'Deleted automatically when the parent user row is deleted (CASCADE). '
    'Application enforces at most one is_default = true per user_id.';
COMMENT ON COLUMN user_addresses.label IS
    'Free-form label supplied by the customer, e.g. "Casa", "Trabajo". Nullable.';
COMMENT ON COLUMN user_addresses.country_code IS
    'ISO 3166-1 alpha-2 code (2 characters). CHECK constraint prevents partial inserts.';

-- Query served: load all addresses for a user (profile page, checkout address picker).
CREATE INDEX idx_user_addresses_user ON user_addresses (user_id);

-- ---------------------------------------------------------------------------
-- 5. Table: refresh_token_families
--    One row per login session. Revocation is family-scoped: when reuse of
--    a rotated refresh token is detected, the entire family is revoked so
--    the legitimate user is forced to re-authenticate (security §2.3).
--    14-day absolute lifetime tracked via created_at; no sliding extension.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_token_families (
    id              bigint      GENERATED ALWAYS AS IDENTITY,
    user_id         uuid        NOT NULL,
    revoked         boolean     NOT NULL DEFAULT false,
    revoked_at      timestamptz,
    -- 'LOGOUT' | 'REUSE_DETECTED' | 'PASSWORD_CHANGE' | 'PASSWORD_RESET'
    revoked_reason  varchar(50),
    created_at      timestamptz NOT NULL DEFAULT now(),
    last_used_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_refresh_token_families PRIMARY KEY (id),
    CONSTRAINT fk_refresh_token_families_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_refresh_token_families_revoked_reason
        CHECK (revoked_reason IN ('LOGOUT', 'REUSE_DETECTED', 'PASSWORD_CHANGE', 'PASSWORD_RESET'))
);

COMMENT ON TABLE  refresh_token_families IS
    'One row per login session (security §2.3). '
    'Family lifetime is 14 days absolute from created_at. '
    'Revoke the entire family on logout, reuse-detection, or password reset/change.';
COMMENT ON COLUMN refresh_token_families.revoked_reason IS
    'Allowed values: LOGOUT, REUSE_DETECTED, PASSWORD_CHANGE, PASSWORD_RESET. '
    'Null while the family is active; set when revoked = true.';
COMMENT ON COLUMN refresh_token_families.last_used_at IS
    'Updated on every successful token rotation. Used for session-inventory display '
    'and idle-session detection in future releases.';

-- Query served: "show active sessions for this user"; family-wide revocation lookup.
-- Partial index covers only live (non-revoked) families — keeps it tiny.
CREATE INDEX idx_refresh_token_families_user_active
    ON refresh_token_families (user_id)
    WHERE NOT revoked;

-- ---------------------------------------------------------------------------
-- 6. Table: refresh_tokens
--    One row per rotation step within a family. Strict one-time use:
--    presenting a token that is already marked used triggers family
--    revocation (reuse detection — security §2.3).
--    Token value is NEVER stored; only SHA-256(token) is persisted.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id          bigint      GENERATED ALWAYS AS IDENTITY,
    family_id   bigint      NOT NULL,
    -- SHA-256 hex digest of the opaque random token sent to the client.
    -- The raw token is SecureRandom >= 128 bits (security §6a / §2.3).
    token_hash  text        NOT NULL,
    issued_at   timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz NOT NULL,
    used        boolean     NOT NULL DEFAULT false,
    used_at     timestamptz,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_family
        FOREIGN KEY (family_id) REFERENCES refresh_token_families (id) ON DELETE CASCADE,
    CONSTRAINT ck_refresh_tokens_expiry
        CHECK (expires_at > issued_at),
    CONSTRAINT ck_refresh_tokens_used_at
        CHECK ((used = false AND used_at IS NULL) OR (used = true AND used_at IS NOT NULL))
);

COMMENT ON TABLE  refresh_tokens IS
    'One row per rotation step. Strictly one-time use (security §2.3). '
    'Presenting a used token → revoke the whole family and return 401. '
    'ON DELETE CASCADE from refresh_token_families handles bulk cleanup on revocation.';
COMMENT ON COLUMN refresh_tokens.token_hash IS
    'SHA-256 of the opaque token value delivered to the client. '
    'The plaintext token never touches the database. '
    'Unique constraint prevents hash collisions (astronomically unlikely, defended anyway).';
COMMENT ON COLUMN refresh_tokens.used_at IS
    'Populated atomically with used = true. '
    'CHECK constraint enforces that used and used_at are always consistent.';

-- Query served: validation of a presented refresh token (point lookup by hash).
CREATE UNIQUE INDEX uq_refresh_tokens_hash ON refresh_tokens (token_hash);

-- Query served: family-wide revocation scan; "is there still an active token in this family?"
-- Partial index skips already-used tokens (majority of rows over time).
CREATE INDEX idx_refresh_tokens_family_active
    ON refresh_tokens (family_id)
    WHERE NOT used;

-- ---------------------------------------------------------------------------
-- 7. Table: password_reset_tokens
--    Single-use, short-TTL tokens mailed to the user during the password-
--    reset flow (security §2.6). Stored hashed; the plaintext link is
--    emailed and never retained server-side.
-- ---------------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
    id          bigint      GENERATED ALWAYS AS IDENTITY,
    user_id     uuid        NOT NULL,
    -- SHA-256 of the full-entropy token embedded in the reset link.
    token_hash  text        NOT NULL,
    expires_at  timestamptz NOT NULL,
    used        boolean     NOT NULL DEFAULT false,
    used_at     timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_password_reset_tokens_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT ck_password_reset_tokens_used_at
        CHECK ((used = false AND used_at IS NULL) OR (used = true AND used_at IS NOT NULL))
);

COMMENT ON TABLE  password_reset_tokens IS
    'Single-use password-reset tokens. TTL <= 1 hour from created_at (security §2.6). '
    'Requesting a new token must invalidate any prior unused token for the same user '
    '(application responsibility; DB enforces uniqueness of the hash, not of the user).';
COMMENT ON COLUMN password_reset_tokens.token_hash IS
    'SHA-256 of the SecureRandom >= 128-bit token embedded in the reset email link. '
    'Invalid / expired / used tokens all return the same generic 400 (anti-enumeration §2.6).';

-- Query served: validation of a reset link (lookup by hash, skipping already-used tokens).
CREATE UNIQUE INDEX uq_password_reset_tokens_hash ON password_reset_tokens (token_hash);

-- Partial index for the active (unused) subset — the relevant set for validation.
CREATE INDEX idx_password_reset_tokens_active
    ON password_reset_tokens (token_hash)
    WHERE NOT used;

-- ---------------------------------------------------------------------------
-- 8. Table: admin_audit_log
--    Append-only record of every admin action (security §6c).
--    Two-level enforcement:
--      DB level  — ecommerce_app role: INSERT + SELECT only (see §9 grants).
--      App level — AuditRepository exposes insert/read only; ArchUnit asserts this.
--    No FK on actor_id: if a user row is ever deleted the audit must survive.
--    actor_email is denormalised for the same reason.
--    Retention >= 1 year; no purge path in v1 (ADR required to change this).
-- ---------------------------------------------------------------------------
CREATE TABLE admin_audit_log (
    id           bigint      GENERATED ALWAYS AS IDENTITY,

    -- Soft reference: intentionally no FK to users.id so the log survives
    -- user deletion. actor_email is the durable human-readable identity.
    actor_id     uuid        NOT NULL,
    actor_email  text        NOT NULL,

    -- 'PRODUCT_CREATED', 'ORDER_CANCELLED_BY_ADMIN', etc.
    action_type  varchar(100) NOT NULL,

    -- Target resource type and id stored as text to avoid FK coupling and
    -- to survive target deletion (database-design §3.7 rationale).
    entity_type  varchar(50),
    entity_id    text,

    -- Before/after state or relevant context. PII minimised to what the
    -- action touched; credentials/secrets scrubbed before persistence.
    details      jsonb,

    ip_address   inet,
    occurred_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_admin_audit_log PRIMARY KEY (id)
);

COMMENT ON TABLE  admin_audit_log IS
    'Append-only admin action log (security §6c). '
    'ecommerce_app role has INSERT + SELECT only — no UPDATE or DELETE. '
    'Retention >= 1 year. Any purge/archival policy requires an ADR and product-owner sign-off.';
COMMENT ON COLUMN admin_audit_log.actor_id IS
    'UUID of the acting admin at action time. No FK — log must outlive the user row.';
COMMENT ON COLUMN admin_audit_log.actor_email IS
    'Email of the acting admin, denormalised. Survives user deletion; provides '
    'human-readable accountability even if the user row is gone.';
COMMENT ON COLUMN admin_audit_log.details IS
    'JSONB payload: before/after state, correlation id, and any action-specific context. '
    'Credentials, raw tokens, and full PII beyond what the action touched must be scrubbed '
    'before this column is populated (security §2.8 log-scrubbing rules).';
COMMENT ON COLUMN admin_audit_log.entity_type IS
    'Domain resource type, e.g. ''Product'', ''Order'', ''Coupon''. '
    'No FK — target row may be deleted without invalidating the audit record.';
COMMENT ON COLUMN admin_audit_log.entity_id IS
    'String representation of the target resource id (UUID or other). '
    'Stored as text to avoid FK coupling and to accommodate heterogeneous id types.';

-- Query served: admin review screen "what happened to entity X?" (by type + id, descending time).
CREATE INDEX idx_audit_target
    ON admin_audit_log (entity_type, entity_id, occurred_at DESC);

-- Query served: admin review screen "what did admin Y do?" (by actor, descending time).
CREATE INDEX idx_audit_actor
    ON admin_audit_log (actor_id, occurred_at DESC);

-- Query served: time-range queries across all actions (monitoring dashboards, retention sweep).
CREATE INDEX idx_audit_occurred_at
    ON admin_audit_log (occurred_at DESC);

-- ---------------------------------------------------------------------------
-- 9. Application role and least-privilege grants
--    The role is created idempotently so this migration is safe to replay
--    against a DB where the role already exists (e.g., after a repair run).
--    Password is a placeholder; actual value injected via environment
--    (security §5.1 — no secrets in migration files).
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = 'ecommerce_app'
    ) THEN
        -- Password placeholder — overridden at provisioning time via ALTER ROLE
        -- or the DB connection string supplied through environment variables.
        CREATE ROLE ecommerce_app LOGIN PASSWORD 'SET_VIA_ENV';
    END IF;
END;
$$;

-- Schema-level access
GRANT CONNECT ON DATABASE ecommerce TO ecommerce_app;
GRANT USAGE   ON SCHEMA  public     TO ecommerce_app;

-- users: application performs SELECT / INSERT / UPDATE (soft-lock, update attempts).
-- DELETE is intentionally withheld — users are deactivated, never deleted, while
-- downstream contexts (orders, carts) reference them via RESTRICT FKs.
GRANT SELECT, INSERT, UPDATE ON users TO ecommerce_app;

-- user_addresses: full CRUD permitted (customers may add/edit/remove addresses).
GRANT SELECT, INSERT, UPDATE, DELETE ON user_addresses TO ecommerce_app;

-- Refresh token family lifecycle: create on login, update on rotation/revocation.
GRANT SELECT, INSERT, UPDATE ON refresh_token_families TO ecommerce_app;

-- Refresh tokens: create on issue, update to mark used; no delete (CASCADE handles it).
GRANT SELECT, INSERT, UPDATE ON refresh_tokens TO ecommerce_app;

-- Password reset tokens: create on request, update to mark used.
GRANT SELECT, INSERT, UPDATE ON password_reset_tokens TO ecommerce_app;

-- admin_audit_log: INSERT and SELECT ONLY. UPDATE and DELETE are permanently denied
-- at the DB level (security §6c, database-design §3.7). This is the second enforcement
-- layer; the application layer (AuditRepository) enforces the same contract in code.
GRANT SELECT, INSERT ON admin_audit_log TO ecommerce_app;

-- bigint identity sequences (used by all GENERATED ALWAYS AS IDENTITY columns above).
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO ecommerce_app;
