-- =============================================================================
-- V002__create_catalog_schema.sql
-- Context  : catalog
-- Purpose  : Bootstrap the catalog schema.
--            Creates: categories, products, product_images.
--            Grants  : ecommerce_app role with least-privilege surface.
--            Trigger : reuses set_updated_at() defined in V001 for
--                      categories.updated_at and products.updated_at.
--
-- Does NOT touch: users, user_addresses, refresh_token_families,
-- refresh_tokens, password_reset_tokens, admin_audit_log, or any other V001
-- object. admin_audit_log already exists (V001 §8) and is already granted
-- SELECT, INSERT to ecommerce_app; it is a shared, cross-context table, not
-- auth-specific, and is intentionally left alone here. The catalog
-- application layer will INSERT into it directly (backend-lead concern).
--
-- Safety analysis
-- ---------------
-- Lock profile  : Three brand-new, empty tables (categories, products,
--                 product_images). ACCESS EXCLUSIVE locks are taken only on
--                 these new relations as they are created — no existing
--                 V001 table (users, etc.) is touched, so there is zero lock
--                 contention with anything already live. All indexes here
--                 (including the partial index and the lower(name)
--                 functional index) are built on tables containing zero rows
--                 at migration time, so plain CREATE INDEX is safe and fast;
--                 CREATE INDEX CONCURRENTLY is not required (that concern
--                 applies to adding indexes to already-populated hot tables
--                 in later migrations, not here).
-- Destructive?  : No. Greenfield creation only; no ALTER/DROP of existing
--                 objects.
-- Backfill?     : No data exists in these tables yet.
-- Forward-fix   : N/A — no previous version of categories/products/
--                 product_images to break. This migration itself must not
--                 break the app version deployed alongside V001 only; it is
--                 purely additive from that version's point of view.
-- Rollback      : DROP TABLE product_images, then products, then categories
--                 (reverse FK dependency order). Dev only; production
--                 follows expand-migrate-contract — a new forward version,
--                 never an edit of this file.
-- Testcontainer : Verified from clean (V001 -> V002 on an empty database) and
--                 from previous version (schema at V001, then apply V002) per
--                 the flyway skill's mandatory two-path test rule.
-- Applied       : 2026-07-31  (append-only — never modify after first apply)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Table: categories
--    Category tree for catalog navigation/filtering (database-design §1, §2).
--    Self-referencing parent_id models the tree; NULL parent_id = root
--    category. ID is UUIDv7, generated application-side (ADR-0002 + security
--    §6a), same convention as users.id in V001: no DEFAULT on id — omitting
--    it forces every INSERT to supply one explicitly, so a missing id fails
--    loudly instead of silently falling back to a DB-generated value.
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id          uuid         NOT NULL,
    parent_id   uuid,
    name        varchar(150) NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT pk_categories PRIMARY KEY (id),

    -- Reference data is never cascade-deleted (database-design §6). Deleting
    -- a category that still has children fails loudly; the child must be
    -- re-parented or removed first.
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE RESTRICT
);

COMMENT ON TABLE  categories IS
    'Category tree for catalog navigation/filtering. One row per category, '
    'self-referencing via parent_id to form the tree. Deletion of a category '
    'still referenced by a child category or a product fails (RESTRICT FKs) '
    '-- re-parent/reassign first, then delete.';
COMMENT ON COLUMN categories.id IS
    'UUIDv7 generated by the application before INSERT (ADR-0002). '
    'No DB default -- omitting id in an INSERT is a programmer error, not a silent fallback.';
COMMENT ON COLUMN categories.parent_id IS
    'Self-referencing FK. NULL = root category. ON DELETE RESTRICT: a category '
    'with children cannot be deleted while those children still point to it.';
COMMENT ON COLUMN categories.name IS
    'Display name of the category. varchar(150) caps length at the column level; '
    'uniqueness of name is NOT enforced -- sibling categories in different '
    'branches of the tree may legitimately share a name.';

-- Trigger: keep updated_at synchronised on every UPDATE row.
-- Reuses set_updated_at(), defined once in V001; not redefined here.
CREATE TRIGGER trg_categories_updated_at
    BEFORE UPDATE ON categories
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- Query served: category-tree traversal -- "list children of category X"
-- (breadcrumb building, admin tree view, recursive CTE descent).
CREATE INDEX idx_categories_parent ON categories (parent_id);

-- ---------------------------------------------------------------------------
-- 2. Table: products
--    Aggregate root of the catalog bounded context (database-design §1, §2).
--    Never deleted (PO rule 10) -- retirement is a status change
--    (status = 'RETIRED'), enforced below by withholding DELETE at the grant
--    level (§4) as the second layer, on top of the application never
--    exposing a delete path.
--    ID is UUIDv7, generated application-side; no DB default, same rationale
--    as categories.id / users.id above.
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id           uuid          NOT NULL,
    category_id  uuid          NOT NULL,
    sku          text          NOT NULL,

    -- ACTIVE / RETIRED. text + CHECK is preferred over a native enum --
    -- adding a value is ALTER TABLE (cheap), not CREATE TYPE + dependency
    -- juggling (matches users.role / refresh_token_families.revoked_reason
    -- convention in V001).
    status       text          NOT NULL DEFAULT 'ACTIVE',

    -- Money convention (database-design §4): numeric(19,4) amount + char(3)
    -- ISO 4217 currency code, always paired, never float/money.
    base_price   numeric(19,4) NOT NULL,
    currency     char(3)       NOT NULL,

    name         text          NOT NULL,
    description  text,

    created_at   timestamptz   NOT NULL DEFAULT now(),
    updated_at   timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT pk_products PRIMARY KEY (id),

    -- Reference data is never cascade-deleted (database-design §6). A
    -- category with existing products cannot be deleted.
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,

    CONSTRAINT ck_products_status
        CHECK (status IN ('ACTIVE', 'RETIRED')),
    CONSTRAINT ck_products_base_price
        CHECK (base_price >= 0),
    CONSTRAINT ck_products_currency
        CHECK (char_length(currency) = 3)
);

COMMENT ON TABLE  products IS
    'Product identity, current base price, and ACTIVE/RETIRED status. '
    'Never deleted (PO rule 10) -- retiring a product is a status change, '
    'never a DELETE. ecommerce_app is granted SELECT/INSERT/UPDATE only '
    '(no DELETE, see §4) as the DB-level backstop for this rule.';
COMMENT ON COLUMN products.id IS
    'UUIDv7 generated by the application before INSERT (ADR-0002). '
    'No DB default -- omitting id in an INSERT is a programmer error, not a silent fallback.';
COMMENT ON COLUMN products.category_id IS
    'Owning category. NOT NULL -- every product belongs to exactly one '
    'category in v1 (no multi-category assignment). ON DELETE RESTRICT: the '
    'category cannot be deleted while this product references it.';
COMMENT ON COLUMN products.sku IS
    'Merchant-assigned stock-keeping unit. Unique across the catalog '
    '(uq_products_sku, §3) -- used for admin/import lookups.';
COMMENT ON COLUMN products.status IS
    'ACTIVE (default) or RETIRED. Retired products are excluded from catalog '
    'browse/search (idx_products_category_active, §3) but their row, and any '
    'historical order_items/cart_items referencing them, are never removed.';
COMMENT ON COLUMN products.base_price IS
    'Current list price. numeric(19,4) per the Money convention -- always '
    'paired with currency, never a bare float. Historical prices at time of '
    'sale live as snapshot columns on order_items/cart_items, not here.';
COMMENT ON COLUMN products.currency IS
    'ISO 4217 alpha-3 currency code (e.g. USD, EUR) paired with base_price. '
    'CHECK constraint enforces the fixed 3-character length.';
COMMENT ON COLUMN products.description IS
    'Long-form marketing copy. Nullable; intentionally unbounded text '
    '(product descriptions are not user-submitted free text subject to the '
    'general no-unbounded-text guidance -- they are merchant/admin authored).';

-- Trigger: keep updated_at synchronised on every UPDATE row.
-- Reuses set_updated_at(), defined once in V001; not redefined here.
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- Query served: admin/import lookup by SKU; also the uniqueness guard for
-- PO rule "SKU identifies exactly one product".
CREATE UNIQUE INDEX uq_products_sku ON products (sku);

-- Query served: catalog browse/filter -- category page, ACTIVE-only listing,
-- sorted/filtered by price. Partial (WHERE status = 'ACTIVE') keeps the
-- index limited to the sellable subset; RETIRED products never appear in
-- this scan path. Composite (category_id, base_price) supports both the
-- equality predicate and the price sort/range in one index.
CREATE INDEX idx_products_category_active
    ON products (category_id, base_price)
    WHERE status = 'ACTIVE';

-- Query served: v1 product-name prefix search (e.g. "name starts with ...",
-- case-insensitive), via `WHERE lower(name) LIKE lower(:prefix) || '%'`.
-- Deliberately a plain btree functional index, NOT GIN/pg_trgm/trigram --
-- full-text/trigram search is out of scope for v1 and deferred to a future
-- ADR with measured need (database-design §5, indexing skill rule 6). Do
-- not "upgrade" this to GIN without that ADR.
CREATE INDEX idx_products_name_lower ON products (lower(name));

-- ---------------------------------------------------------------------------
-- 3. Table: product_images
--    Ordered image URLs per product -- owned child rows within the Product
--    aggregate, exactly like user_addresses under users in V001. Unlike the
--    RESTRICT rule for products/categories themselves, CASCADE is correct
--    here: an image has no existence independent of its product.
--    PK is bigint identity -- internal child row, never client-addressed as
--    an aggregate root (ADR-0002 ID conventions / database-design §4).
-- ---------------------------------------------------------------------------
CREATE TABLE product_images (
    id            bigint      GENERATED ALWAYS AS IDENTITY,
    product_id    uuid        NOT NULL,
    image_url     text        NOT NULL,

    -- No DEFAULT: every INSERT must supply an explicit position, same
    -- fail-loudly rationale as the app-generated ids above -- there is no
    -- safe implicit value when multiple images are being attached to the
    -- same product in the same request.
    display_order int         NOT NULL,

    created_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_product_images PRIMARY KEY (id),
    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT ck_product_images_display_order
        CHECK (display_order >= 0)
);

COMMENT ON TABLE  product_images IS
    'Ordered image URLs belonging to a product. Deleted automatically when '
    'the parent product row is deleted (CASCADE) -- note that in practice '
    'products are never deleted (PO rule 10), so this CASCADE exists for '
    'schema correctness/dev-cleanup rather than a routine production path. '
    'Application enforces a stable, gapless-or-not-but-unique render order '
    'per product via uq_product_images_product_display (§3).';
COMMENT ON COLUMN product_images.image_url IS
    'Fully-qualified image URL (CDN or object-storage location). No length '
    'cap beyond the implicit text limit -- URLs are opaque, app-validated.';
COMMENT ON COLUMN product_images.display_order IS
    'Zero-based render position among a product''s images. NOT NULL, no '
    'default (caller must assign explicitly). CHECK (>= 0) rejects negative '
    'positions; uq_product_images_product_display (§3) rejects two images '
    'at the same position for the same product.';

-- Query served: uniqueness invariant -- "at most one image per position per
-- product" -- and doubles as the lookup index for reordering/upsert-by-slot.
CREATE UNIQUE INDEX uq_product_images_product_display
    ON product_images (product_id, display_order);

-- Query served: "load all images for product X, in order" (product detail
-- page). Leading column alone also covers the FK/CASCADE delete path.
CREATE INDEX idx_product_images_product ON product_images (product_id);

-- ---------------------------------------------------------------------------
-- 4. Least-privilege grants for ecommerce_app
--    Role already exists (created idempotently in V001); no CREATE ROLE
--    here. Schema-level USAGE ON SCHEMA public was already granted in V001
--    and is not scoped per-table, so it is not repeated.
-- ---------------------------------------------------------------------------

-- products: application performs SELECT / INSERT / UPDATE only. DELETE is
-- intentionally withheld -- products are retired via status = 'RETIRED',
-- never deleted (PO rule 10, database-design §1 table inventory). This is
-- the DB-level backstop: even a buggy or compromised application code path
-- cannot issue a DELETE that the role isn't permitted to execute.
GRANT SELECT, INSERT, UPDATE ON products TO ecommerce_app;

-- categories: full CRUD, including DELETE, is granted here.
-- Judgment call / rationale: unlike products, no domain rule (ADR-0001 or
-- database-design) forbids deleting a category outright -- "category CRUD"
-- is explicitly planned at the application layer, and the fk_categories_parent
-- / fk_products_category ON DELETE RESTRICT guards already make an unsafe
-- delete impossible at the DB level (an attempt to delete a category that
-- still has child categories or products fails loudly rather than silently
-- orphaning/cascading). Granting DELETE here does not reopen the hazard that
-- RESTRICT on products specifically defends against (silent data loss of
-- product rows); it only allows removing a category once it is empty, which
-- is a legitimate admin operation (e.g. cleaning up an unused leaf node).
-- If this judgment is wrong for the intended admin UX, narrow this grant to
-- SELECT, INSERT, UPDATE in a follow-up migration -- do not edit this file.
GRANT SELECT, INSERT, UPDATE, DELETE ON categories TO ecommerce_app;

-- product_images: full CRUD permitted -- fully app-managed child rows within
-- the Product aggregate, same as user_addresses under users in V001.
GRANT SELECT, INSERT, UPDATE, DELETE ON product_images TO ecommerce_app;

-- bigint identity sequences created in this migration (product_images.id).
-- V001's blanket GRANT USAGE ON ALL SEQUENCES IN SCHEMA public only covered
-- sequences that existed at the time V001 ran; it does not retroactively
-- cover sequences created by later migrations, so it is replicated here.
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO ecommerce_app;
