spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_dev
    username: ecommerce_dev
    password: ${DB_PASSWORD:dev_password_only_local}

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
